sudo: required
dist: trusty
language: bash

before_install:
  - sudo add-apt-repository ppa:jacob/virtualisation -y
  - sudo apt-get -qq update
  - sudo apt-get install -y bsdtar kpartx qemu-user-static haveged libtalloc2 dosfstools pigz wget make
  - wget -q http://download.opensuse.org/repositories/home:/cedric-vincent/xUbuntu_14.04/amd64/proot_5.1.0-1_amd64.deb
  - sudo dpkg -i proot_5.1.0-1_amd64.deb

script:
  - sudo make build

before_deploy:
  - mkdir -p /home/travis/build/NYUMusEdLab/musedboxbase/releases
  - pigz -f --best < /srv/builddir/img/rpi2-musedboxbase.img > /home/travis/build/NYUMusEdLab/musedboxbase/releases/rpi2-musedboxbase-${TRAVIS_TAG}.img.gz
deploy:
  provider: releases
  api_key:
    secure: "ITuczA8aL43XRuifAmS03e6hJywxBbACSb5zZDjSCXFk38/gTTHiwW3IWj47meBv1scSmzBbI0fZKMhWO5LwBor7nZO1OrKH7U5/mGQ3jvcNKLkqmKj9CXwxyYK35bLLzx1RZA9kFHEIH8E2xL8mnnbpQaJDCa+mO5JDP261xIl1wwkw1p/O4VOnCsU1GyEVxn580gJAmP6K0Uieox1KOiwFncfMoLc47msvni4my/9ZglB9mRvN3fxXR3YxN9chbS9vF59AVyWcpeJh82Gxek4F27p1rZWxay2+fbQAsdKcbJrZIKwW29yPpNDg+PN9c0rEFSwAXRE+qbS69skSKTyUpGvE62aoZ6HtfpRoTZSGCq62dhBHCplPjR/7CIXOZOpSYJq3tToS4iJkSudPZt2lycyctobc3rp40lc+kQEexlnU6F0/1Ah+n1VUIBB3O8lEmE6AWGvf6aMN/Ava7qxoAJqcZnJ4d169uIdzrYtwfzlzUv4NO2/W8YxUIZ6M+bkBkrW+GzzfDMWSwYwhim5EEOpb/G9J0wvNIEgoHnWHSmEFD3uZkgKp8Vx38RQ4rM9VShq01zzIcGnsSr+F1UixMzqMcJ4hShJQoUKFb7N+32W0rJh5n1Cjbx7422nitH+GkCaYeorEtxTF9YwCaB69PVuyULJKST3h9OYnAGg="
  file: /home/travis/build/NYUMusEdLab/musedboxbase/releases/rpi2-musedboxbase-${TRAVIS_TAG}.img.gz
  skip_cleanup: true
  on:
    tags: true
