sudo: required
dist: trusty
language: bash

before_install:
  - sudo add-apt-repository ppa:jacob/virtualisation -y
  - sudo apt-get -qq update
  - sudo apt-get install -y bsdtar kpartx qemu-user-static haveged libtalloc2 dosfstools pigz wget make
  - wget -q http://download.opensuse.org/repositories/home:/cedric-vincent/xUbuntu_14.04/amd64/proot_5.1.0-1_amd64.deb
  - sudo dpkg -i proot_5.1.0-1_amd64.deb

script:
  - sudo make build

before_deploy:
  - mkdir -p /home/travis/build/NYUMusEdLab/musedboxbase/releases
  - pigz -f --best < /srv/builddir/img/rpi2-musedboxbase.img > /home/travis/build/NYUMusEdLab/musedboxbase/releases/rpi2-musedboxbase-${TRAVIS_TAG}.img.gz
deploy:
  provider: releases
  api_key:
    secure: "QP1Aos+p0m+FTzviBABjXE3VIT5KQq35PnV0DoFhgoAk0LLTaQBJmtvCXVURjiWmx5d6xjuUzfw6/E5kLLcbnb4yWEXZvYKKYT2JkUAPm0BdYRLWoQtYpGop5ovmTpo3K8ULoBKjvl/W+KRv4eTahmqwmNTU4/FUg+ws1SWLe1ryq6YyFrhy0J5IhUtsAweBitt4iQ+8sHBm4lCHKVA00w+TGqgaDUzzWBeejnPzJOh5DauFzT2czIi8fI3ezshowAlEQaFYopjwDR1+2eqet1SMu+WpzV1271MXTQqvO/gU9OCygyk9S5qTnfaWnxH5mz3+DbLkh9+eF8nI3ljD5jdd9f6U7RSB9rT/NCucp4kYFjCA+bT/mbwgnyYSY1rvsfjCRvFKDjK8hTxn2Ao9boaITIUtAfHQkrrXe+/r7Q69ztkOZ0+vi397MQoMC42jvP2bN+SY2Q/jTadMrX1kVpQMb/WbA2w8Lu8AsjF7wEYMEim3/kmqrh3hy+ChGgfr/ip8RwXOmTTFdaS55HvbHpmfgR10xJJmBxFU1IXv/YJSeCjEbLs2NLeEqAyVuFO7vcy4N511aUuEFu3U5zakg3GjDLbfk9Ig1iW1hM+EwrCZMjcO8QY9C3rFE0MFuYMLOLfa8LB7tWUFSExNRqKZ8/XPHt0uqEq3keTwT3zPA8U="
  file: /home/travis/build/NYUMusEdLab/musedboxbase/releases/rpi2-musedboxbase-${TRAVIS_TAG}.img.gz
  skip_cleanup: true
  on:
    tags: true
